### ISSUE TITLE
Cannot access website with data

### ISSUE THREAD

**Issue by sofroniewn** [SMLM-Challenge/Challenge2016#3]
Hello, I'm trying to access bigwww.epfl.ch/smlm/ to download the data, but keep on getting timeout errors. Is that the same for everyone else? Thanks!

**Comment by HazenBabcock** [comment]
The downloads seem to work for me. Is there one in particular that you are trying to download? I could test.

**Comment by sofroniewn** [comment]
It's working now. The whole was down last time I tried. Who knows if problem was on my end or not. Glad that it works now and expectation was that it should. Thanks!!
